### ISSUE TITLE
multimc5 install path

### ISSUE THREAD

**Issue by marcmagus** [EfficiencyVI/adcmmp#1]
The Arch AUR package for multimc5 installs the executable at /usr/bin/multimc5, and stores files in ~/.multimc5

I just edited my local version of your very fine script so it would detect (and launch) my existing install, but I thought I'd mention it; it would be nice if there were a simple variable to edit at the top of the script (or if you detected that possible install location, but I know that can get out of hand)

**Comment by EfficiencyVI** [comment]
Thank you! Next on my list is alternative path for instances and the executable.

**Comment by EfficiencyVI** [comment]
Fixed!
